[package]
name = "quick-flash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.17", features = ["derive"] }
etcetera = "0.8.0"
probe-rs = "0.24.0"
rust-s3 = {version = "0.35", default-features = false, features = ["sync", "sync-native-tls"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
toml = "0.8.19"
